---
title: "test"
author: "Nguyen Van A"
date: "2025-01-11"
output: html_notebook
---


```{r include=FALSE}
if (!require(viridis)) { install.packages("viridis") }
if (!require(rmarkdown)) { install.packages("rmarkdown") }
if (!require(languageserver)) { install.packages("languageserver") }
library(viridis) # for color
library(rmarkdown) # for html_notebook
library(knitr) # for tables
```
https://rmarkdown.rstudio.com/lesson-1.html

Markdown standard format text

- **bold**
- *italic*
- heading: # heading 1: ## heading 2: ### heading 3: #### heading 4: ##### heading 5: ######
- [link](https://www.google.com)
- [link with title](https://www.google.com "Google")
- `code`
- latex equation: $E=mc^2$



# plot function

```{r}
# Define the function to differentiate
f <- function(x) log(x) / (1 + x)
# Generate x values
x_values <- seq(1, 8, 0.1)
# Correctly plot the function
plot(x_values, f(x_values), type = "l",
     xlab = "x", ylab = "f(x)",
     main = "Plot of f(x) = log(x)/(1+x)")
# plot derivative
f_prime <- function(x) 1 / (x * (1 + x)) - log(x) / (x * (1 + x))^2
plot(x_values, f_prime(x_values), type = "l",
     xlab = "x", ylab = "f'(x)",
     main = "Plot of f'(x) = 1/(x*(1+x)) - log(x)/(x*(1+x))^2")

```

```{r}
# Add labels for better clarity
image(volcano, col = viridis(200),
      main = "Volcano Data",
      xlab = "Longitude",
      ylab = "Latitude")
```

# tables

```{r echo=FALSE, results = "asis"}
# Create a table
table_data <- data.frame(
  Name = c("Alice", "Bob", "Charlie"),
  Age = c(25, 30, 35),
  Score = c(85, 90, 88)
)
kable(table_data, caption = "Table 1: Student Data", format = "html")
```

